#!/bin/sh
#
# $Id$
#
# A script to run the test harnesses for PlainSocketImpl and
# PlainDatagramSocketImpl ie TCP/IP and UDP/Multicast IP
#
SRCDIR=`dirname $PWD`
CLASSPATH=$SRCDIR/jipsy.jar:/usr/java/lib/classes.zip:.
LD_LIBRARY_PATH=$SRCDIR/lib
export LD_LIBRARY_PATH CLASSPATH
PATH=/usr/java/bin:$PATH
JAVA=$SRCDIR/bin/j

SPORT=7
echo "Testing TCP/IP Client/Server Interaction"
# First test tcp client connecting to IPv4 echo server
$JAVA PSITestClient 127.0.0.1 $SPORT 10.1.1.1 23000

# test tcp client connecting to IPv6 echo server
$JAVA PSITestClient ::1 $SPORT ::1 23020

# test tcp client connecting to IPv6 echo server
$JAVA PSITestClient 127.0.0.1 $SPORT ::1 23040

# start echo server
$JAVA PSITestServer &
SERVERPID=$!
SPORT=27000
sleep 2
# First test tcp client connecting to IPv4 echo server
$JAVA PSITestClient 127.0.0.1 $SPORT 10.1.1.1 24000

# test tcp client connecting to IPv6 echo server
$JAVA PSITestClient ::1 $SPORT ::1 24020

# test tcp client connecting to IPv4 echo server
$JAVA PSITestClient 127.0.0.1 $SPORT ::1 24040

kill $SERVERPID

# start echo server binding to an IPv6 address only
SPORT=27001
$JAVA PSITestServer ::1 $SPORT 5 &
SERVERPID=$!
sleep 2

# test tcp client connecting to IPv6 echo server
$JAVA PSITestClient ::1 $SPORT ::1 24020

kill $SERVERPID

# start echo server binding to an IPv4 address only
SPORT=27002
$JAVA PSITestServer 10.1.1.1 $SPORT 5 &
SERVERPID=$!
sleep 2
# First test tcp client connecting to IPv4 echo server
$JAVA PSITestClient 10.1.1.1 $SPORT 10.1.1.1 24000

# test tcp client connecting to IPv6 echo server
$JAVA PSITestClient 10.1.1.1 $SPORT ::1 24020

kill $SERVERPID

SPORT=7
echo ""
echo "Testing UDP/IP client/server interaction"
$JAVA PDSITestClient 127.0.0.1 $SPORT 10.1.1.1 25000
$JAVA PDSITestClient ::1 $SPORT ::1 25100
$JAVA PDSITestClient 127.0.0.1 $SPORT ::1 25200

SPORT=28000
$JAVA PDSITestServer &
SERVERPID=$!
sleep 2
$JAVA PDSITestClient 127.0.0.1 $SPORT 10.1.1.1 29000
$JAVA PDSITestClient ::1 $SPORT ::1 29100
$JAVA PDSITestClient 127.0.0.1 $SPORT ::1 29200

kill $SERVERPID
