#!/bin/sh
#
# $Id$
#
# A script to run the test harnesses for PlainSocketImpl and
# PlainDatagramSocketImpl ie TCP/IP and UDP/Multicast IP
#
SRCDIR=`dirname $PWD`
CLASSPATH=$SRCDIR/jipsy.jar:/usr/java/lib/classes.zip:.
LD_LIBRARY_PATH=$SRCDIR/lib
export LD_LIBRARY_PATH CLASSPATH
PATH=/usr/java/bin:$PATH

SPORT=7
echo "Testing TCP/IP Client/Server Interaction"
# First test tcp client connecting to IPv4 echo server
java PSITestClient 127.0.0.1 $SPORT 10.1.1.1 23000

# test tcp client connecting to IPv6 echo server
java PSITestClient ::1 $SPORT ::1 23020

# test tcp client connecting to IPv6 echo server
java PSITestClient 127.0.0.1 $SPORT ::1 23040

# start echo server
java PSITestServer &
SERVERPID=$!
SPORT=27000
sleep 2
# First test tcp client connecting to IPv4 echo server
java PSITestClient 127.0.0.1 $SPORT 10.1.1.1 24000

# test tcp client connecting to IPv6 echo server
java PSITestClient ::1 $SPORT ::1 24020

# test tcp client connecting to IPv4 echo server
java PSITestClient 127.0.0.1 $SPORT ::1 24040

kill $SERVERPID

# start echo server binding to an IPv6 address only
SPORT=27001
java PSITestServer ::1 $SPORT 5 &
SERVERPID=$!
sleep 2

# test tcp client connecting to IPv6 echo server
java PSITestClient ::1 $SPORT ::1 24020

kill $SERVERPID

# start echo server binding to an IPv4 address only
SPORT=27002
java PSITestServer 10.1.1.1 $SPORT 5 &
SERVERPID=$!
sleep 2
# First test tcp client connecting to IPv4 echo server
java PSITestClient 10.1.1.1 $SPORT 10.1.1.1 24000

# test tcp client connecting to IPv6 echo server
java PSITestClient 10.1.1.1 $SPORT ::1 24020

kill $SERVERPID

echo ""
echo "Testing UDP/IP client/server interaction"
java PDSITest 127.0.0.1 7 10.1.1.1 25000
java PDSITest ::1 7 ::1 25100
java PDSITest 127.0.0.1 7 ::1 25200
