/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_net_InetAddress */

#ifndef _Included_java_net_InetAddress
#define _Included_java_net_InetAddress
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_net_InetAddress
 * Method:    pton
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_java_net_InetAddress_pton
  (JNIEnv *, jclass, jstring);

/*
 * Class:     java_net_InetAddress
 * Method:    getLoopbackAddress
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_java_net_InetAddress_getLoopbackAddress
  (JNIEnv *, jclass);

/*
 * Class:     java_net_InetAddress
 * Method:    getAnyLocalAddress
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_java_net_InetAddress_getAnyLocalAddress
  (JNIEnv *, jclass);

/*
 * Class:     java_net_InetAddress
 * Method:    getLocalHostName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_java_net_InetAddress_getLocalHostName
  (JNIEnv *, jclass);

/*
 * Class:     java_net_InetAddress
 * Method:    getAllHostAddresses
 * Signature: (Ljava/lang/String;)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_java_net_InetAddress_getAllHostAddresses
  (JNIEnv *, jclass, jstring);

/*
 * Class:     java_net_InetAddress
 * Method:    getHostByAddress
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_java_net_InetAddress_getHostByAddress
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
