/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_net_PlainSocketImpl */

#ifndef _Included_java_net_PlainSocketImpl
#define _Included_java_net_PlainSocketImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef java_net_PlainSocketImpl_DEBUG
#define java_net_PlainSocketImpl_DEBUG 0L
/*
 * Class:     java_net_PlainSocketImpl
 * Method:    accept
 * Signature: (Ljava/net/SocketImpl;)V
 */
JNIEXPORT void JNICALL Java_java_net_PlainSocketImpl_accept
  (JNIEnv *, jobject, jobject);

/*
 * Class:     java_net_PlainSocketImpl
 * Method:    available
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_java_net_PlainSocketImpl_available
  (JNIEnv *, jobject);

/*
 * Class:     java_net_PlainSocketImpl
 * Method:    bind
 * Signature: (Ljava/net/InetAddress;I)V
 */
JNIEXPORT void JNICALL Java_java_net_PlainSocketImpl_bind
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     java_net_PlainSocketImpl
 * Method:    getOption
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_net_PlainSocketImpl_getOption
  (JNIEnv *, jobject, jint);

/*
 * Class:     java_net_PlainSocketImpl
 * Method:    listen
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_java_net_PlainSocketImpl_listen
  (JNIEnv *, jobject, jint);

/*
 * Class:     java_net_PlainSocketImpl
 * Method:    setOption
 * Signature: (ILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_java_net_PlainSocketImpl_setOption
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     java_net_PlainSocketImpl
 * Method:    socketClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_net_PlainSocketImpl_socketClose
  (JNIEnv *, jobject);

/*
 * Class:     java_net_PlainSocketImpl
 * Method:    socketConnect
 * Signature: (Ljava/net/InetAddress;I)V
 */
JNIEXPORT void JNICALL Java_java_net_PlainSocketImpl_socketConnect
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     java_net_PlainSocketImpl
 * Method:    socketCreate
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_java_net_PlainSocketImpl_socketCreate
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
